name: "Build (Linux)"

on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: bash ./scripts/ci-install-deps-linux.sh
    - run: bash ./scripts/ci-build-linux.sh

    - name: 'Archive CLI binary'
      uses: actions/upload-artifact@v2
      with:
        name: hyperhotp
        path: build/hyperhotp

    - name: 'Archive GUI binary'
      uses: actions/upload-artifact@v2
      with:
        name: hyperhotp_gui
        path: build/hyperhotp_gui
