name: "Build (Linux)"

on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: bash ./scripts/ci-install-deps-linux.sh
    - run: bash ./scripts/ci-build-linux.sh
