name: "Build (Windows)"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: "MINGW64"
        update: true
        install: >-
          git
          make
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-libusb

    - name: 'Build'
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_STATIC=ON
        cmake --build build

    - name: 'Archive binaries'
      uses: actions/upload-artifact@v2
      with:
        name: hyperhotp.exe
        path: build/hyperhotp.exe
